---
title: "assignment_2_almond_yield"
author: "Adelaide Robinson"
date: "2023-04-20"
output: html_document
---

```{r setup, include=FALSE}
library(tidyverse)
library(here)
```

```{r loading the data}

### -----------------------
# Loading the data
### -----------------------

# reading in the text file
data <- read.table(here("clim.txt"), header = TRUE)

```


```{r running the function}

### -----------------------
# Running the function w/ default years
### -----------------------

# sourcing the function from the R project
source("almond_yield.R")

default_anomaly <- almond_yield(climate_data = data)



kableExtra::kable(default_anomaly, align = "c") |> 
  kableExtra::kable_styling(bootstrap_options = "striped", 
                            full_width = FALSE)

```

```{r}

### -----------------------
# Running the function w/ new years
### -----------------------

# sourcing the function from the R project
source("almond_yield.R")

year3_anomaly <- almond_yield(years = c(2000:2003) , climate_data = data)



kableExtra::kable(year3_anomaly, align = "c") |> 
  kableExtra::kable_styling(bootstrap_options = "striped", 
                            full_width = FALSE)

```

